### ISSUE TITLE
Variable name with no prefix fails if the default namespace is the XProc namespace

### ISSUE THREAD

**Issue by argv-minus-one** [ndw/xmlcalabash1#103]
Calabash 1.0.9 gives me a bogus error if I try to declare a variable with no prefix when the default namespace is the XProc namespace. For instance:

``` xml
<pipeline xmlns="http://www.w3.org/ns/xproc">
    <variable name="some-variable" select="…"/>
</pipeline>
```

The error is:

```
You cannot specify a variable in the p: namespace.
```

This is bogus because, per [the XProc spec §5.7.1](http://www.w3.org/TR/xproc/#p.variable), a variable name with no prefix is in no namespace, not the current default namespace.

**Comment by ndw** [comment]
Yep. That was bogus.
