### ISSUE TITLE
XSLT 2 - No Result Document Error

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#110]
If an XSLT 2.0 stylesheet only produces results via xsl:result-document, there will be no primary result document.  As such, the "result" output port will be an empty sequence.  I believe this should be an error according to the XProc specification.

**Comment by alexmilowski** [comment]
Github ... so ... broken.  Can't attach a pipeline to an issue because that would be _normal_.  Reason #1 not to use github.

Enjoy your cut-n-paste:

<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
   xmlns:c="http://www.w3.org/ns/xproc-step" 
   version="1.0" exclude-inline-prefixes="c">
   <p:output port="result" sequence="true"/>
   <p:xslt name="chunker" version="2.0">
      <p:input port="source">
         <p:inline><doc/>/p:inline
      /p:input
      <p:input port="stylesheet">
         <p:inline>
            <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               version="2.0">
               <xsl:template match="/">
                  <xsl:result-document href="output.xml">
                     <secondary/>
                  /xsl:result-document
               /xsl:template
            /xsl:stylesheet
         /p:inline
      /p:input
      <p:input port="parameters"><p:empty/>/p:input
   /p:xslt
   <p:identity>
      <p:input port="source">
         <p:pipe port="result" step="chunker"/>
         <p:pipe port="secondary" step="chunker"/>
      /p:input
   /p:identity
   
   <p:for-each>
      <p:template>
         <p:input port="template">
            <p:inline>
               <uri>{base-uri(/)}</uri>
            /p:inline
         /p:input
         <p:input port="parameters"><p:empty/>/p:input
      /p:template
   /p:for-each
/p:declare-step

**Comment by alexmilowski** [comment]
Crap sandwich.  Cut-n-paste gets interpreted.

**Comment by alexmilowski** [comment]
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
   xmlns:c="http://www.w3.org/ns/xproc-step" 
   version="1.0" exclude-inline-prefixes="c">
   <p:output port="result" sequence="true"/>
   <p:xslt name="chunker" version="2.0">
      <p:input port="source">
         <p:inline><doc/></p:inline>
      </p:input>
      <p:input port="stylesheet">
         <p:inline>
            <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               version="2.0">
               <xsl:template match="/">
                  <xsl:result-document href="output.xml">
                     <secondary/>
                  </xsl:result-document>
               </xsl:template>
            </xsl:stylesheet>
         </p:inline>
      </p:input>
      <p:input port="parameters"><p:empty/></p:input>
   </p:xslt>
   <p:identity>
      <p:input port="source">
         <p:pipe port="result" step="chunker"/>
         <p:pipe port="secondary" step="chunker"/>
      </p:input>
   </p:identity>
   <!-- for debugging -->
   <p:for-each>
      <p:template>
         <p:input port="template">
            <p:inline>
               <uri>{base-uri(/)}</uri>
            </p:inline>
         </p:input>
         <p:input port="parameters"><p:empty/></p:input>
      </p:template>
   </p:for-each>
</p:declare-step>
```

**Comment by ndw** [comment]
Yes. The XSLT step specifically avoids calling this an error. Useful, but probably not conforming.

I guess I should make it an error.

**Comment by alexmilowski** [comment]
For the record, I see this as an error in our XProc specification.  It really shouldn't be an error for XSLT 2.0.

**Comment by ndw** [comment]
I raised https://github.com/xproc/specification/issues/1 to track this issue. I think I'm going to leave the current behavior alone.
