### ISSUE TITLE
JEuclid / FOP - MathML doesn't render

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#111]
JEuclid's fop extension for MathML should load automatically (it's a service) but it doesn't work.  I put the jeuclid jars in the classpath but the XSL step still complains about the MathML. 

This feels like a invocation issue within the p:xsl-formatter step implementation for FOP.

**Comment by ndw** [comment]
Can you attach a small FO document that contains some MathML for me to use as a test? I'll assume I can find JEuclid if I go looking on the web...

**Comment by alexmilowski** [comment]
Non-image attachments aren't supported for github issues.  I'll send you an e-mail.

**Comment by alexmilowski** [comment]
Here's a sample FO document and example output.

On Fri, Aug 2, 2013 at 5:46 AM, Norman Walsh notifications@github.comwrote:

> Can you attach a small FO document that contains some MathML for me to use
> as a test? I'll assume I can find JEuclid if I go looking on the web...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ndw/xmlcalabash1/issues/111#issuecomment-22003350
> .

## 

--Alex Milowski
"The excellence of grammar as a guide is proportional to the paucity of the
inflexions, i.e. to the degree of analysis effected by the language
considered."

Bertrand Russell in a footnote of Principles of Mathematics

**Comment by alexmilowski** [comment]
Oh look, and e-mail reply strips the attachments.  Nice feature.

**Comment by alexmilowski** [comment]
Here's my alternate calabash invocation script:

``` #!/bin/bash
installdir=`dirname $0`
java -cp "$installdir/lib/*.jar" -cp $installdir/calabash.jar com.xmlcalabash.drivers.Main $*
```
