### ISSUE TITLE
p:step-available('p:validate-with-relax-ng') returns true when p:validate-with-relax-ng is not available

### ISSUE THREAD

**Issue by josteinaj** [ndw/xmlcalabash1#117]
When Jing is not on the classpath, p:validate-with-relax-ng doesn't work. However, `p:step-available('p:validate-with-relax-ng')` still returns `true`. Shouldn't it return `false`?

The same probably goes for the other steps which requires external libraries, although I haven't tested those...

**Comment by ndw** [comment]
Yes, that's a good point. I'll see about fixing that.

**Comment by ndw** [comment]
After some investigation, I don't think this is practical. 

Realistically, all that p:step-available can tell (in XML Calabash v1.x) is whether or not the step can be instantiated, not whether or not it will run successfully. I think you'll have to use p:try/p:catch to deal with runtime errors.

I'll try to do better in the V.next architecture.

**Comment by ndw** [comment]
Changed my mind. :-)

**Comment by ndw** [comment]
There. That's better.
