### ISSUE TITLE
Extension stubs artifact

### ISSUE THREAD

**Issue by sharwell** [ndw/xmlcalabash1#122]
Hi Norm,

To help with future Maven releases, I have created a new artifact with the artifact ID `xmlcalabash-extension-stubs`. This library contains stub interfaces and classes for the various non-public products XML Calabash supports through extensions (all methods in this artifact throw `UnsupportedOperationException`). The stubs artifact allows xmlcalabash artifact to use the following in pom.xml:

``` xml
<dependency>
  <groupId>com.xmlcalabash</groupId>
  <artifactId>xmlcalabash-extension-stubs</artifactId>
  <version>1.0.0</version>
  <scope>provided</scope>
</dependency>
```

This tells Maven to use the stubs library so all the extensions can successfully compile for anyone. The [`<scope>provided</scope>`](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) line means this is not a transitive dependency; to _use_ the extensions users will still have to separately obtain the necessary libraries.

My big question for you is how you want to manage this artifact:
1. Do you want to create a new repository for this artifact, or simply include this artifact in a subfolder of the xmlcalabash1 repository?
2. If you want a new repository, do you want to create a new repository under your account, or have me place it under mine?
3. If you want the artifact in a subfolder, can you suggest the name of the desired subfolder so I can move it there before sending a pull request?

Thanks,
Sam

**Comment by ndw** [comment]
I'm not sure what kind of artifact this is. How much stuff are we talking about?

Does resources/maven seem like a sensible place?

**Comment by sharwell** [comment]
It seems to be reasonable to me. I'll check a few other projects where this is relevant and see if there is an existing standard practice before finalizing the decision.

I'll send a pull request tomorrow with the update.

**Comment by ndw** [comment]
Did you send the pull request?

**Comment by sharwell** [comment]
Hi Norm,

The change is prepared, but I am waiting on the following items before I can send a pull request:
1. It is currently a commit based on the result of #124. If you merge that change, it will simplify the change to include the extension stubs.
2. I don't have permission to upload files to Maven Central with the group ID `com.xmlcalabash`. As such, one of the following two things would need to happen before the stubs artifact can actually be used in the build:
   1. You can add a comment on the issue [OSSRH-3139](https://issues.sonatype.org/browse/OSSRH-3139) to request that the user `sharwell` be given permission to publish artifacts with the group ID `com.xmlcalabash`.
   2. I could instead publish the stubs artifact with the group ID `com.rackspace.xmlcalabash` instead of `com.xmlcalabash` (I have permission for the former).

Thanks,
Sam

**Comment by ndw** [comment]
Ok. Maven's all borked again. But I think I've commited the fixes for 124. So please, feel free! (And thanks, in advance.)

**Comment by sharwell** [comment]
The build problem is due to the addition of an `org.restlet` dependency. That functionality needs to be refactored to a standalone artifact; in the meantime I corrected the Maven build by excluding all the piperack files from the build adding optional Maven dependencies on `org.apache.jena:apache-jena-libs`, `org.semarglproject:semargl-core`, and `org.semarglproject:semargl-rdfa`, with a comment that code using the `cx:rdf-load`, `cx:rdf-store`, or `cx:sparql` steps will need to add a dependency on those libraries (but only those users).

**Comment by ndw** [comment]
So I can fix that by adding the org.restlet jars to the lib directory in the distribution then?

**Comment by ndw** [comment]
Maven distribution works with gradle, I believe.
