### ISSUE TITLE
Obscure Error with p:template

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#127]
I get this error from a malformed p:template (invalid closing curly brace expression):

Oct 09, 2013 11:39:23 AM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: err:XC0067:XC0067
Oct 09, 2013 11:39:23 AM com.xmlcalabash.drivers.Main error
SEVERE: Unknown error

the invocation is:

```
<p:template>
<p:with-param name="position" select="'1'"/>
<p:input port="template">
    <p:inline>
        <sample href="sample-{$position}}.xml"/>
    </p:inline>
</p:input>
</p:template>
```

which is invalid because of the double closing curly bracket.

**Comment by ndw** [comment]
Uhm. I agree the error message is ugly, but the template spec says:

```
It is a dynamic error (err:XC0067) to encounter a single closing curly brace “}”
that is not immediately followed by another closing curly brace.
```
