### ISSUE TITLE
p:iteration-position() in p:template

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#128]
Not sure if this should work but using p:iteration-position() in a bracket expression in p:template causes an error.  The p:template note seems rather silent on whether these extension functions should be available.

**Comment by ndw** [comment]
Can you post an example. It should work in p:with-param, it won't work in the body of the template.

I believe that Sections 2.6.2.1 and 2.6.2.2 answer the question about whether or not they should be available (they should not).
