### ISSUE TITLE
docs/BUGS is pointless

### ISSUE THREAD

**Issue by Zearin** [ndw/xmlcalabash1#14]
The content of `docs/BUGS` feels like a yucky bureaucratic runaround.  

I recommend one of the following:
- Adjusting your test suite results to write to this file
- Making this a symlink to the test suite results
- As a minimal, last resort: At least **point the user in the right direction** to find the test suite failures

**Comment by ndw** [comment]
Indeed. I think I'll just remove that.

**Comment by Zearin** [comment]
**SQUASH!** :)
