### ISSUE TITLE
Split Sequence recompile XPath at each iteration

### ISSUE THREAD

**Issue by innovimax** [ndw/xmlcalabash1#143]
It seems like Split Sequence recompiles XPath at each iteration on the sequence
https://github.com/ndw/xmlcalabash1/blob/6f6f8b90be6eb4cfc982568320eaf28a9723451b/src/com/xmlcalabash/library/SplitSequence.java#L103

You could unwrap the compilation of the XPath expression very easily and only let the creation of the dynamic context in the loop

https://github.com/ndw/xmlcalabash1/blob/6f6f8b90be6eb4cfc982568320eaf28a9723451b/src/com/xmlcalabash/library/SplitSequence.java#L120

**Comment by ndw** [comment]
Ok
