### ISSUE TITLE
HTML5 doctype name should be lower case

### ISSUE THREAD

**Issue by josteinaj** [ndw/xmlcalabash1#149]
Reproduce with this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">

    <p:store href="file:/tmp/tmp.xml" method="html" version="5.0">
        <p:input port="source">
            <p:inline exclude-inline-prefixes="#all">
                <html xmlns="http://www.w3.org/1999/xhtml"/>
            </p:inline>
        </p:input>
    </p:store>

</p:declare-step>
```

The doctype in the output is `<!DOCTYPE HTML>`. It should be `<!DOCTYPE html>`.

**Comment by ndw** [comment]
I believe this is a bug in Saxon. I've reported it: http://saxon.markmail.org/search/?q=list%3Asaxon-help#query:list%3Asaxon-help+page:1+mid:tg55l3ptubcysmdc+state:results

**Comment by rdeltour** [comment]
As replied in the `saxon-help` list, this is not strictly-speaking a bug: [the HTML5 doctype is case-insensitive](http://www.w3.org/TR/html5/syntax.html#the-doctype)

**Comment by ndw** [comment]
Ultimately, the serialization is performed by Saxon so I'm going to close this without prejudice.
