### ISSUE TITLE
synchronization of runtime load?

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#15]
I am trying to load the same pipeline via the same runtime simultaneously and it looks like you need to wrap the runtime in a synchronization block.

This will fail in two different threads:

runtime.load(...same uri...) 

This will succeed:

synchronized (runtime) {
   runtime.load(...same uri...)
}

It seems like overkill to do it this way but the interior of the XProcRuntime instance would need to guarantee thread safety.

**Comment by ndw** [comment]
Can you say more about where you think this synchronization needs to be?
