### ISSUE TITLE
Support XHTML5 serialization on p:store

### ISSUE THREAD

**Issue by josteinaj** [ndw/xmlcalabash1#150]
[Section 6.1.2 of the XSLT and XQuery Serialization 3.0 spec](http://www.w3.org/TR/xslt-xquery-serialization-30/#XHTML_HTML_VERSION) describes a new attribute on `xsl:output` called `html-version` which, if `method="xhtml"`, lets you specify that the output should be serialized according to XHTML5 by setting `html-version="5.0"`.

Could this be exposed on `p:store` as `cx:html-version`?

**Comment by ndw** [comment]
Until such time as the underlying Saxon processor supports html-version, it won't have any effect.

I'll leave this issue open until then and then I'll add something to support it.

**Comment by ndw** [comment]
I implemented a workaround. When Saxon supports the underlying options, that'll work too.

**Comment by josteinaj** [comment]
Cool! So how do I use it?

**Comment by ndw** [comment]
I suppose it would have been nice if I'd included that!

See http://xmlcalabash.com/docs/reference/langext.html#ext.html-serializer
