### ISSUE TITLE
p:http-request and base URIs

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#153]
I believe the current implementation does not set the base URI of a retrieved document.

I would expect:

<c:request method="GET" href="http://www.example.com/sample.xml"/>

to set the base URI to "http://www.example.com/sample.xml" when retrieved through p:http-request.  I'm not sure this is a requirement as the specification seems a bit silent about base URIs and the results of using the p:http-request step.

**Comment by ndw** [comment]
Definitely a bug.
