### ISSUE TITLE
pxf:delete/@recursive="true" fails

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#155]
Let's start with that everything works in 1.0.16-95.

I get these errors on a simple delete of a directory:

May 12, 2014 7:18:21 PM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: subset-epub.xpl:30:33:Cannot delete: file does not exist
May 12, 2014 7:18:21 PM com.xmlcalabash.drivers.Main error
SEVERE: com.xmlcalabash.core.XProcException: Cannot delete: file does not exist
May 12, 2014 7:18:21 PM com.xmlcalabash.drivers.Main error
SEVERE: Underlying exception: java.io.FileNotFoundException: /Users/alex/workspace/tdo/build/Book.epub.tmp/META-INF/container.xml is not a directory

I can't recreate the error with a small test case but the test case I created fails to do anything in 1.0.17-95 or 1.0.18-95.

**Comment by alexmilowski** [comment]
Github stinks for attachments to issues.

**Comment by alexmilowski** [comment]
```
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
    xmlns:c="http://www.w3.org/ns/xproc-step" version="1.0"
    xmlns:pxf="http://exproc.org/proposed/steps/file"
   >
   <p:import href="http://xmlcalabash.com/extension/steps/library-1.0.xpl"/>
   <pxf:delete href="tmp" recursive="true" fail-on-error="false"/> 
</p:declare-step>
```

**Comment by alexmilowski** [comment]
```
<project basedir="." default="build-test" name="Build Test">
<target name="build-test">
<mkdir dir="tmp"/>
<mkdir dir="tmp/test"/>
<echo file="tmp/a.txt">A</echo>
<echo file="tmp/test/b.txt">B</echo>
</target>
</project>
```

**Comment by ndw** [comment]
Yeah. I see where it's broken. Sigh. Some patches I wish I'd reviewed more closely...

It'll take a little longer to fix than I have just at the moment. I'll try to fix it tonight.

**Comment by ndw** [comment]
I think this is fixed in the code I just pushed to the saxon95 branch

**Comment by ndw** [comment]
I wonder if I just un-did this change with that directory fix. Will try when I get a chance.

**Comment by ndw** [comment]
Fixed, I believe.
