### ISSUE TITLE
Strange Error from Validation after XInclude Fails

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#160]
I put an XInclude into the XProc 1.0 spec with an xpointer() scheme and got this:

calabash -isource=langspec.xml -oresult=,langspec.xml \
                    ../style/validate.xpl schema=../schema/dbspec.rng
Jun 18, 2014 10:32:38 AM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: file:/Users/alex/workspace/github/xproc10/style/validate.xpl:9:25:err:XD0023:Expression could not be evaluated: /|*
Jun 18, 2014 10:32:38 AM com.xmlcalabash.drivers.Main error
SEVERE: It is a dynamic error if an XPath expression is encountered which cannot be evaluated (because it is syntactically incorrect, contains references to unbound variables or unknown functions, or for any other reason).
Jun 18, 2014 10:32:38 AM com.xmlcalabash.drivers.Main error
SEVERE: Underlying exception: java.lang.NullPointerException

I think it comes from the XInclude failing and leaving something strange behind.

**Comment by alexmilowski** [comment]
Maybe this will help:

```
diff --git a/langspec/standard-components.xml b/langspec/standard-components.xml
index cbd4548..a39b3d8 100644
--- a/langspec/standard-components.xml
+++ b/langspec/standard-components.xml
@@ -556,7 +556,8 @@ including an entity body (content) for the request.</para>
 <p:declare-step type="p:http-request">
   <p:input port="source"/>
   <p:output port="result"/>
-  &serialization-options;
+  <xi:include href="serialization-options.xml" xpointer="xmlns(p=http://www.w3.org/ns/xproc)xpath(/p:declare-step/p:option)" parse="xml"/>
+  <!--&serialization-options;-->
 </p:declare-step>
```

**Comment by ndw** [comment]
Nope. I copied the langspec directory, created the serialization-options.xml file, replaced the entity references in standard-components.xml with xi:includes as shown and ran this pipeline:

```
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0"
                xmlns:c="http://www.w3.org/ns/xproc-step"
                xmlns:cx="http://xmlcalabash.com/ns/extensions"
                xmlns:exf="http://exproc.org/standard/functions"
                exclude-inline-prefixes="cx exf"
                name="main">
<p:input port="source"/>
<p:input port="parameters" kind="parameter"/>
<p:output port="result"/>
<p:serialization port="result" indent="true"/>

<p:xinclude/>

<p:validate-with-relax-ng>
  <p:input port="schema">
    <p:document href="/projects/w3c/WWW/XML/XProc/github/specification/schema/dbspec.rng"/>
  </p:input>
</p:validate-with-relax-ng>


</p:declare-step>
```

Worked for me.

If you can reproduce it with a test case, feel free to reopene it.
