### ISSUE TITLE
Wrong sequence order on p:xslt secondary port with Saxon EE

### ISSUE THREAD

**Issue by rdeltour** [ndw/xmlcalabash1#166]
When using Saxon EE, the order in which the secondary result trees are produced as documents on the secondary port of `p:xslt` is apparently random.

See this [simple repro](https://gist.github.com/rdeltour/b3cb582ad4cb187dce87) (tested with latest oXygen v16, running Calabash v1.0.18-95).
It works OK when Calabash is running with Saxon HE or PE, but produces documents in a random order with Saxon EE.

A quick look at [OutputURIResolver](http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/lib/OutputURIResolver.html) showed no mention of concurrency-related caveats with EE, but I didn't look too far.

**Comment by rdeltour** [comment]
This issue will probably need to be somehow forwarded to Saxonica, but as far as I understand the way final result trees are passed to an application is implementation-defined in XSLT 2.0, so it doesn't seem to be a bug in Saxon (but causes a bug in Calabash, AFAIU).

**Comment by rdeltour** [comment]
So, I [asked on saxon-help](http://saxon.markmail.org/thread/arpgg6fx3e2i3eym) and Michael Kay pointed me to the relevant [change of behavior from 9.4 to 9.5](http://www.saxonica.com/documentation/index.html#!changes/optimization/9.4-9.5)

Long story short: the `xsl:result-document` instruction is now asynchronous. EE can fall back to a single-thread mode using the `FeatureKeys.RESULT_DOCUMENT_THREADS` config option.

Now, I dunno if this should be done silently in Calabash or left at the discretion of users. It sounds like 99% of users would expect the secondary port to reflect XSLT's processing order, but once again the combination of XSLT 2.0 and XProc 1.0 spec language does not unambiguously guarantee that. WDYT ? Should I file a spec RFE somewhere ?

**Comment by ndw** [comment]
I don't see anywhere in the XProc spec where we suggest there's an ordering. In what sense does the order seem wrong?

I'm happy to add support for the RESULT_DOCUMENT_THREADS feature, if that helps...

**Comment by rdeltour** [comment]
> I don't see anywhere in the XProc spec where we suggest there's an ordering.

Indeed: all the spec says is "all other result documents appear on the secondary port".

> In what sense does the order seem wrong?

In the sense that XSLT 2.0 defines the concept of ["sorted sequence"](http://www.w3.org/TR/xslt20/#dt-sorted-sequence), so I always assumed that final result trees produced during processing of a sorted sequence (e.g. in the `xsl:for-each` of my example gist above) would appear in the same order on the `secondary` port.

I now understand that neither XSLT nor XProc guarantees that but:
- I think it would be more readable and less error-prone if the spec at least explicitly adds that to the list of _implementation defined_ features.
- I believe that ideally there should be a **language** feature to make that order respected (e.g. an option on the `p:xslt` step).

As an example, the scenario where I was hit by this is the following: during an HTML to EPUB 3 conversion, I chunk the single HTML source in an XSLT by producing secondary final result trees with  `xsl:result-document` in a  `xsl:for-each` (say, for each top-level section). Obviously, the order matters since I need the result sequence of HTML documents to match to original reading order.
Instead, I ended up with Alice in Wonderland starting with Chapter III, followed by Chapter I, then Chapter II, then the Introduction, etc. !

> I'm happy to add support for the RESULT_DOCUMENT_THREADS feature, if that helps...

I'm equally happy to configure it externally for now, but again EE's behavior looks very error-prone to me.

**Comment by fgeorges** [comment]
Just in case it can help...  The result of an XSLT transform is a) a main output tree and b) a set of named secondary output trees.  Each secondary output tree has a different name (which is a URI).  There is no relative order defined between secondary output trees, and I would not recommend depending on any "happens to be in that order" accidental discovery.

**Comment by rdeltour** [comment]
> There is no relative order defined between secondary output trees

Yes, I understand that (and thanks for clarifying anyway). But if I understand correctly there _is_ a notion of processing a sequence in sorted order. Can it be leveraged from XProc's perspective ?
Alternatively, what about an option to be able to "sort" documents on their base URI ?

I could see a `p:sort` in XProc 2.0 standard step library :wink:

**Comment by fgeorges** [comment]
Yes, a sequence (as per XDM) is a set of items in specific order.  But the set of secondary output trees is not a sequence (each is constructed from a sequence though).  XSLT does not define any "order" between the secondary output trees (it is a set, it would not make any sense).  XProc could have defined such an order on the port "secondary", but did not.  So yes, if you want to rely on a specific order, sorting on the document URI is your only possibility I guess...

**Comment by rdeltour** [comment]
Right. Since this is obviously not a Calabash bug, let me close this issue.

I'm wondering if defining secondary output trees as a sequence would be (theoretically) possible though –as I believe it would be a good fit to XProc's sequence-based processing model– and if yes, what's the rationale for the decision to make that a set.

Anyway, sorry for the fuss and thanks for the brain cycles.

@ndw where can I file a request to add an explicit "implementation defined" caveat to XProc spec ? Are you now using [GitHub's xproc/specification issue tracker](https://github.com/xproc/specification/issues)  ?

**Comment by ndw** [comment]
Yes, that's the place to raise it @rdeltour
