### ISSUE TITLE
Why does file:///path get translated to file:/path

### ISSUE THREAD

**Issue by ndw** [ndw/xmlcalabash1#172]
And when did it start happening?

**Comment by ndw** [comment]
The culprit is File.toURI:

``` java
   File f = new File("/tmp/base.xml");
   System.out.println(f.toURI());
```

prints `file:/tmp/base.xml`.

http://docs.oracle.com/javase/7/docs/api/java/net/URI.html says, in part, "... any URI u that does not contain redundant syntax such as two slashes before an empty authority (as in file:///tmp/ )..." so I think it's intentional and "correct."

/cc @alexmilowski

**Comment by alexmilowski** [comment]
It wouldn't be the first time that Java did the wrong thing.
