### ISSUE TITLE
Custom Configuration for XProcConfiguration

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#18]
I'd like to instantiate the XProcConfiguation with my own XML document (or a location of one) so I can tweak the default step implementations.  Currently, the constructor will call "loadConfiguration()".  Later, I can call "parse()" with my own XML but the configuration has already loaded itself at that point.

My use case: I want to replace the implementation of p:http-request.

**Comment by ndw** [comment]
If you specify different implementations in your custom config file, they'll take precedence. I think just calling parse() on your own XML config is the right answer. Do you disagree?

**Comment by ndw** [comment]
Assuming not.
