### ISSUE TITLE
Pipeline hanging when invoked from CL

### ISSUE THREAD

**Issue by wendellpiez** [ndw/xmlcalabash1#180]
A pipeline inexplicably hangs when Calabash is invoked from the CL (in Windows), while it works under oXygen.

An example is given here: https://github.com/wendellpiez/Luminescent/tree/master/calabash-test

(The batch file shows what I try to do using a Windows 7 command line.)

In the pipeline, currently, a plain string is resolved internally by the XSLT at the front end of the pipe. using unparsed-text(), allowing me to pass in a URI to the (plain-text) LMNL syntax file. I would be just as happy (indeed I might prefer) if Calabash could bring me the plain text from the URI itself, using p:data or by other means, as long as it could be parameterized at runtime. I am investigating doing something with --data-input text/plain@LMNLport=uri and will try that next.

However, it remains curious that I am able to execute the pipeline as given in oXygen (as demonstrated in the project file there) while not when using Calabash from the CL.

Thanks for the good work on this Norm!

**Comment by ndw** [comment]
At a first guess (and I can say this because I've done it several times myself), I think you're pipeline is simply waiting for input on `stdin`. You're effectively doing this:

```
C:\Bin\xmlcalabash-1.0.21-95\calabash LMNL-xLMNL.xpl lmnl-file=../../advicetoacaterpillar.lmnl
```

and `LMNL-xLMNL.xpl` has an input port named source. Since you didn't specify `-isource=somefile`, XML Calabash is reading it from `stdin`.

I think.

**Comment by wendellpiez** [comment]
Norm, I like the theory. I can presumably plug this hole in the XProc.

In general, do you think I am better off using -d-data-input to get my
plain text stream into my pipeline? Or can I parameterize p:data/@href
somehow? If so, the XProc could wrap it in an innocuous document element
and present it to the first XSLT that way (which it knows how to accept).
Among other problems this would allow me to provide URIs relative to the
XProc not the XSLT.

Thanks Norm,

On Mon, Oct 27, 2014 at 12:33 PM, Norman Walsh notifications@github.com
wrote:

> At a first guess (and I can say this because I've done it several times
> myself), I think you're pipeline is simply waiting for input on stdin.
> You're effectively doing this:
> 
> C:\Bin\xmlcalabash-1.0.21-95\calabash LMNL-xLMNL.xpl lmnl-file=../../advicetoacaterpillar.lmnl
> 
> and LMNL-xLMNL.xpl has an input port named source. Since you didn't
> specify -isource=somefile, XML Calabash is reading it from stdin.
> 
> I think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ndw/xmlcalabash1/issues/180#issuecomment-60623492.

## 

Wendell Piez | http://www.wendellpiez.com
XML | XSLT | electronic publishing
Eat Your Vegetables
_____oo_________o_o___ooooo____ooooooo_^

**Comment by ndw** [comment]
If you want the pipeline to get the text document on its primary input port, then --data-input is probably the way to go. If the pipeline doesn't need to read its primary input port then you can just remove it.

**Comment by ndw** [comment]
I think this is resolved. Feel free to reopen if you think I'm wrong.
