### ISSUE TITLE
Feature: Option to turn off p:try/p:catch exception stack trace

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#19]
It should be possible to turn off any exception generated by a p:try/p:catch.  For example, when the p:load fails, I don't want to see the stack trace:

com.xmlcalabash.core.XProcException: Cannot open resource riap://component/milowski.com/foo, status Not Found (404) - The server has not found anything matching the request URI
    at org.atomojo.server.xproc.XProcCache$2.resolve(XProcCache.java:187)
    at com.xmlcalabash.util.XProcURIResolver.resolve(Unknown Source)
    at com.xmlcalabash.util.XProcURIResolver.parse(Unknown Source)
    at com.xmlcalabash.core.XProcRuntime.parse(Unknown Source)
    at com.xmlcalabash.library.Load.run(Unknown Source)
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
       ...

from the pipeline:

<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
                xmlns:c="http://www.w3.org/ns/xproc-step"
                version="1.0"
                name="test">
<p:option name="base"/>
<p:option name="remaining"/>
<p:output port="result"/>

<p:try>
   <p:group>
      <p:load>
      <p:with-option name='href' select="concat($base,$remaining)"/>
      /p:load
   /p:group
   <p:catch>
      <p:identity>
         <p:input port="source">
         <p:inline>
         <http xmlns='http://www.atomojo.org/V/HTTP/2011/1/0' status='404'/>
         /p:inline
         /p:input
      /p:identity
   /p:catch
/p:try

/p:declare-step

**Comment by ndw** [comment]
Fixed. You won't get stack traces anymore unless you enable debugging.
