### ISSUE TITLE
HTTPS download links for compiled versions or checksums would be nice

### ISSUE THREAD

**Issue by rwdalpe** [ndw/xmlcalabash1#197]
Right now the only way I can see to get the latest pre-compiled versions of Calabash are to download the files from http://xmlcalabash.com/download/

There are no securely transmitted checksums for the files to be downloaded, and https://xmlcalabash.com/download is served under a self-signed certificate not trusted by the browser (at least not by Firefox 35.0.1).

Short of building the software yourself, I don't see a quick way of verifying that you have downloaded untampered versions. Any version in maven repositories or other secured locations do not appear to be at the latest version. 

It would be nice to be able to pull in calabash as part of automated builds and have some way of double checking you have safe files.

Possible solution would be to upload the compiled ZIPs currently posted to xmlcalabash.com to the Releases page of this github repository, as the releases page supports HTTPs links.

**Comment by rwdalpe** [comment]
I just saw that the releases page and http://xmlcalabash.com/download are populated with HTTPS links now, and the Maven repository is up-to-date. Thank you very much!

**Comment by ndw** [comment]
You're welcome. Getting all the ducks lined up to make Travis CI publish releases and Gradle to publish to Maven was a challenge, but I think it was worth it.
