### ISSUE TITLE
Enhancement: Metadata about Static Resources

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#20]
For systems that want to detect when an ancillary file has changed and so pipelines need to be re-loaded, it would be nice to get a list of statically configured pipeline resources (e.g. things pointed to by p:document/@href).

**Comment by ndw** [comment]
Do you want a step that returns this information, or an internal API that you can call?

**Comment by ndw** [comment]
Please re-open this issue when you have a chance to provide more details.

**Comment by alexmilowski** [comment]
For my purposes, I need this as an internal API.  I want to be able to test for changes to the pipeline and ancillary files.  The minimum useful API would be one that just returns the URI referenced by any p:document or p:data.

Interestingly, some steps cache and some do not.  As a result, XQuery steps like ml:adhoc-query setup using a p:data will always re-read the the XQuery while an XSLT step with a p:document reference for the stylesheet will not.

**Comment by alexmilowski** [comment]
Oh, and I don't have permission to re-open this issue.  :(
