### ISSUE TITLE
resolver.properties file is ignored

### ISSUE THREAD

**Issue by depify** [ndw/xmlcalabash1#202]
If I put the following resolver.properties file on the classpath
# XMLResolver.properties

relative-catalogs=yes
# Always use semicolons in this list

catalogs=~/catalog.xml

prefer=public
allow-oasis-xml-catalog-pi=yes
cache=~/.xmlresolver/cache

the ~/catalog.xml never gets referred too e.g. xproc only seems to look for a catalog.xml in the directory where xpl is. 

(and yes, I've avoided any of the infinite amount of classpath issues ... I think ... he says entirely confident)

**Comment by ndw** [comment]
Uhm. I don't think I ever claimed to search the classpath for it. Maybe I should. Though maybe this should be a bug on the xmlresolver project.

I think you have to specify it with a Java system property at runtime.

**Comment by depify** [comment]
ok, will investigate where the disconnect is happening

**Comment by ndw** [comment]
Right. Starting with XML Resolver 0.12.3 (which I'll put in the next XML Calabash release), you'll get the feature you wanted.
