### ISSUE TITLE
minor nit - travis build button

### ISSUE THREAD

**Issue by depify** [ndw/xmlcalabash1#207]
points to itself instead of https://travis-ci.org/ndw/xmlcalabash1

**Comment by ndw** [comment]
There what, where?

In README.md, I see

```
[![Build Status](https://travis-ci.org/ndw/xmlcalabash1.svg?branch=saxon96)](https://travis-ci.org/ndw/xmlcalabash1.svg?branch=saxon96)
```

That looks to me like it points to the right place...

**Comment by ndw** [comment]
I can't figure out what problem you were seeing. Please reopen if you think it's still wrong.
