### ISSUE TITLE
Feature: Option to prevent expansion of defaulted attributes

### ISSUE THREAD

**Issue by peetkes** [ndw/xmlcalabash1#21]
It should be possible to turn off the automatic expansion of defaulted attributes. 
Whenever you process XML files with lots of defaulted attributes, the filesize grows enormous because of the defaulted attributes which get expanded.
It would be nice to be able to turn that behaviour (which is in fact default behaviour) off.

**Comment by ndw** [comment]
I added the ability to set Saxon configuration properties in the XML Calabash config file.

**Comment by ndw** [comment]
Released in 0.9.40.
