### ISSUE TITLE
Make it easier to distribute stylesheets and other resources

### ISSUE THREAD

**Issue by ndw** [ndw/xmlcalabash1#210]
Catalog files are great, but they have to be setup by end users. Wouldn't it be nice if complex stylesheets and other packages could be distributed more easily?

Let's try this:
1. XML Calabash searches the jars on the classpath
2. Any `catalog.xml` file that's found at the root of a JAR file is automatically added to the catalog list (if the URIResolver in use supports catalogs, natch')
3. We take special care to work out how to resolve relative URIs in JAR files.

With these changes, a complex set of stylesheets, such as, ahem, the DocBook XSLT 2.0 stylesheets, can be distributed in a JAR file with a catalog. Any pipeline that wants to use DocBook can simply p:import a fixed URI, for example, `http://xmlcalabash.com/pipelines/docbook.xpl`and the right thing will happen.

**Comment by fgeorges** [comment]
Or you can use the packaging system :-)  See the latest installer at http://expath.org/files/pkg (so far `expath-repo-installer-0.13.0.jar`)  It installs everything, bundled with Saxon and Calabash.  It is developed there: https://github.com/fgeorges/expath-pkg-java.  And you can find packages on CXAN, e.g. DocBook at http://cxan.org/pkg/fgeorges/docbook-xsl :-)

All that has already been done, and the same packages work for Calabash, Saxon, eXist, MarkLogic, BaseX...
