### ISSUE TITLE
Calabash does not detect Saxon PE without -a option

### ISSUE THREAD

**Issue by jsulak** [ndw/xmlcalabash1#22]
I'm attempting to use Saxon extension functions in an XSLT called from within a pipeline, but I get the error "Saxon extension functions are not available under Saxon-HE."  However, I am using Saxon PE, so they should be available.  

Using the -a command-line parameter makes it work, but since I'm using Saxon PE instead of EE, it gives a warning.

Here's the command I'm using to launch it:

`java -cp y:\saxon\saxon9pe.jar;y:\saxon\;y:\calabash\calabash.jar com.xmlcalabash.drivers.Main`

I'm using Saxon 9.3.0.11 and Calabash 0.9.40 on Windows 7 64-bit.

**Comment by ndw** [comment]
You can now use the "saxon-processor" option to request a PE processor independent of schema awareness. I just misunderstood the underlying Saxon API, I think. Or it changed when Mike introduced PE. Or something.
