### ISSUE TITLE
Choose based on non-required option doesn't work

### ISSUE THREAD

**Issue by grtjn** [ndw/xmlcalabash1#23]
> This doesn't seem to work in XMLCalabash (0.9.35/0.9.40), am I doing
> something obvious wrong?
> 
>   <p:option name="href" select="''"/>
> 
>   <p:choose name="choose">
>       <p:when test="string-length($href) > 0">
> 
> Whatever gets passed in as $href (I can log to screen, and $href really
> has a value), I always end up in the otherwise..

Reply from ndw:

A quick trace through the code shows that I clearly evaluate the
expression

   boolean(string-length($href) > 0)

and get back the value of the $href variable as the result.

The mind boggles. I'll clearly have to take a deeper look. But, yeah,
I think it's an XML Calabash bug.

**Comment by ndw** [comment]
I'm not sure why Geert's opening message seems so truncated. The thread is here: http://markmail.org/thread/rbj445ztcfzm66uj

The underlying problem is somewhere in my use of the Saxon APIs. That thread is here: http://saxon.markmail.org/thread/2xeuu22ynwl5wciw

**Comment by ndw** [comment]
Michael Kay confirms that this is a Saxon optimization bug. I'll close this as soon as I see a Saxon release that fixes it.

**Comment by ndw** [comment]
Test pipeline, for completeness:

&lt;p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0"
                xmlns:cx="http://xmlcalabash.com/ns/extensions"
                xmlns:c="http://www.w3.org/ns/xproc-step"
                xmlns:l="http://xproc.org/library">
&lt;p:output port="result"/>
&lt;p:option name="href" select="'default'"/>

&lt;p:choose>
  &lt;p:when test="string-length($href) > 0">
    &lt;p:identity>
      &lt;p:input port="source">&lt;p:inline>&lt;doc>not empty&lt;/doc>&lt;/p:inline>&lt;/p:input>
    &lt;/p:identity>
  &lt;/p:when>
  &lt;p:otherwise>
    &lt;p:identity>
      &lt;p:input port="source">&lt;p:inline>&lt;doc>empty&lt;/doc>&lt;/p:inline>&lt;/p:input>
    &lt;/p:identity>
  &lt;/p:otherwise>
&lt;/p:choose>

&lt;/p:declare-step>

**Comment by ndw** [comment]
http://sourceforge.net/tracker/?func=detail&aid=3448231&group_id=29872&atid=397617

Fixed in Saxon 9.4.0.1 will be fixed in any 9.3 release post 9.3.0.11.
