### ISSUE TITLE
`cx:message` attribute for all steps

### ISSUE THREAD

**Issue by josteinaj** [ndw/xmlcalabash1#238]
It would be useful if there were a `cx:message` attribue usable on all steps (anywhere where `cx-depends-on` is allowed), behaving just like the `<cx:message .../>` step. This message would be sent when the step starts its execution. There is currently no other _simple_ way to force a message to be sent right before a step is executed because of the unpredictable order in which steps are executed when piping stuff into ports, options, etc.

**Comment by ndw** [comment]
That's not a bad idea. Note, however, that if all you want is a notice when each step begins, you can simply raise the logging level.

**Comment by josteinaj** [comment]
Yes I do increase the logging level for debugging purposes. Its pretty useful, although it can be difficult at times to know which step it refers to in a big pipeline. In any case, this cx:message suggestion in my use-case is for end-user messages in long-running pipelines. I currently do a lot of piping and cx:depends-on to make sure that cx:message steps execute at the appropriate time and in the correct order.
