### ISSUE TITLE
Establish p:import-able library of definitions for the XML Calabash extension steps

### ISSUE THREAD

**Issue by ndw** [ndw/xmlcalabash1#24]
Give it a fixed URI and use the in-jar version?

**Comment by grtjn** [comment]
Why not remove the need to do that p:import at all? It's not like someone can write an own copy of that file (with different meanings I mean). I don't think that making them always available will slow things down much, right?

**Comment by ndw** [comment]
It's a requirement of the specification, that every step that's used must be explicitly declared. So you can't use cx:zip (for example) unless there's a p:declare-step for it in your pipeline.

Maybe _that_ should change, but that's a spec change not an implementation detail.

In fact, there's already a library of extension steps in the .jar file. I'm just thinking it would be convenient if users could put

<p:import href="http://xmlcalabash.com/steps/extensions.xml"/>

or some such at the top of their pipeline and then be able to use them all.

**Comment by grtjn** [comment]
Hmm, git doesn't seem to treat angular brackets in comments well. (is it possible to edit comments?)

p:xslt isn't declared either right? So I thought why bother declaring additional atomic steps added by the XProc parser. As said, it doesn't do anything.. ;-)

(but a p:import that reads your library from the jar would be quite convenient as well already. almost sounds like you just need a catalogresolver for that..)

**Comment by ndw** [comment]
The steps defined in the p: namespace are an exception, you don't have to declare them. But you do have to declare all the others. I wasn't thinking of a general mechanism for reading libraries from the jar file, though that might be interesting. I was thinking of just a single "magic" URI.

As I was hacking about in Parser.java, I noticed that I may already have implemented this feature :-/, but I haven't taken the time to confirm it.

**Comment by ndw** [comment]
This is already the case:

&lt;p:import href="http://xmlcalabash.com/extension/steps/library-1.0.xpl"/&gt;

imports all of the known extension steps.
