### ISSUE TITLE
p:http-request does not work with Let’s Encrypt certificates

### ISSUE THREAD

**Issue by gimsieke** [ndw/xmlcalabash1#246]
In another context, this could be fixed (for Java 1.8.0_101 or newer) by upgrading to httpclient 4.5.2 instead of 4.2.5 and by using `HttpClientBuilder` instead of `DefaultHttpClient`. This fix was done by someone else in a private repo, but I may send you their patch in private so that you can look into whether this could easily applied to your `p:http-request` extension.

**Comment by ndw** [comment]
I believe this is fixed in 1.1.14, released today.

**Comment by gimsieke** [comment]
It works, thanks a lot!
