### ISSUE TITLE
Output declaration for cx:eval incorrect

### ISSUE THREAD

**Issue by nic-gibson** [ndw/xmlcalabash1#248]
In order for `cx:eval` to handle pipelines that return multiple documents, the declaration for the result output port needs to be updated. In library-1.0.xpl `cx:eval` is declared as:

```
<p:declare-step type="cx:eval">
   <p:input port="pipeline"/>
   <p:input port="source" sequence="true"/>
   <p:input port="options"/>
   <p:output port="result"/>
   <p:option name="step" cx:type="xsd:QName"/>
   <p:option name="detailed" cx:type="xsd:boolean"/>
</p:declare-step>
```

The declaration for the result port should be:

```
   <p:output port="result" sequence="true"/>
```

Using a modified declaration produces the expected output and the java code appears to _do the right thing_ so the only issue appears to be in the declaration itself.

**Comment by ndw** [comment]
This report languished an embarrassing length of time...
