### ISSUE TITLE
typescript pagination is wrong in 41-227T.xml

### ISSUE THREAD

**Issue by Conal-Tuohy** [ndw/xmlcalabash1#263]
In [41-227T](http://45.113.232.64/text/41-227T.html) the page labelled "3" whose transcript starts "Bijara ngundīn" and ends "Boynbărt-a-kau'ain" has the page image below: 

![](http://45.113.232.64/images/41/41-229T.jpg)

In the transcript, the latter 2/3 of the text in that image is marked up as appearing on the next page.

**Comment by gimsieke** [comment]
I’m 99% sure that this issue doesn’t pertain to XML Calabash ;)

**Comment by Conal-Tuohy** [comment]
LOL sorry!
You are dead right @gimsieke
