### ISSUE TITLE
Please don't use insecure repositories

### ISSUE THREAD

**Issue by argv-minus-one** [ndw/xmlcalabash1#265]
As of 8130aca, the build and generated POM use external repositories that are accessed by plain HTTP, not HTTP+TLS (`https` scheme). This exposes everyone who uses or builds this project (including you!) to man-in-the-middle attacks while downloading dependencies for it, injecting malicious code that runs with the full privileges of one's user account.

Please remove or replace these repositories as soon as possible.

**Comment by ndw** [comment]
Fails because maven.restlet.org has a bad cert. :-(

See https://travis-ci.org/ndw/xmlcalabash1/builds/348340392
and https://twitter.com/ndw/status/969634703656529925

**Comment by davidpriest** [comment]
For me,  maven { url "https://maven.restlet.com" } works.

**Comment by ndw** [comment]
It works for me too, but Travis doesn't like it. They must be checking certificates more diligently.

      > Could not resolve org.restlet.jee:org.restlet:2.2.2.
         > Could not get resource 'https://maven.restlet.org/org/restlet/jee/org.restlet/2.2.2/org.restlet-2.2.2.pom'.
            > Could not GET 'https://maven.restlet.org/org/restlet/jee/org.restlet/2.2.2/org.restlet-2.2.2.pom'.
               > Host name 'maven.restlet.org' does not match the certificate subject provided by the peer (CN=restlet.com)

I guess rather than going back to an insecure repository I'll just put them in the project locally for the time being.

**Comment by ndw** [comment]
This appears to be resolved. I've got an https: link to restlet.org and it's working.
