### ISSUE TITLE
Pausing for several minutes after `XML Calabash output BEGIN`

### ISSUE THREAD

**Issue by axfelix** [ndw/xmlcalabash1#268]
We've been running jats2epub (an app that calls XML Calabash -- https://github.com/eirikhanssen/jats2epub) successfully on a server for several years, and for the past several days, we're getting ~5 minute pauses (with no CPU usage) after `NOTICE: XML Calabash output BEGIN`.

I can't duplicate this on another machine, so it's definitely something weird, local to this environment, that's probably not an upstream issue, but I can duplicate with both Java 7 and Java 8. Nothing should've actually changed on the machine other than *maybe* the creation of some weird temporary files somewhere that are causing these issues.

Any idea what may be happening here?

**Comment by axfelix** [comment]
In this environment, even running calabash with the -D flag doesn't print anything for a few minutes.

**Comment by ndw** [comment]
No, that's very odd. Where does the "NOTICE" message come from, that doesn't look familiar to me. 

Have you tried --profile to see if you can identify which step(s) paused?

**Comment by axfelix** [comment]
The "NOTICE" is from the script that wraps it, sorry. Not relevant to debugging as I've established. Even --profile is pausing for the same ~5 minutes without printing anything, like the -D flag...

**Comment by ndw** [comment]
The profile output doesn't show any step having paused?

**Comment by axfelix** [comment]
Nope. Is there an early external lookup that might be failing in our network environment and timing out as of a few weeks ago?

**Comment by ndw** [comment]
I'm a little bit stumped. It sounds like the delay occurs after your notice is printed but before the pipeline even begins running. If you replace your real pipeline with a single identity step, does that also pause for a long time? I wonder if there are JVM debugging flags that can be enabled. You might try cranking the logging up as high as it'll go and see if the pause can be identified between two log messages. Maybe there's a network lookup going on.

**Comment by raducoravu** [comment]
You can also try to use the "jconsole" Java SDK utility to connect to the process and then look at the "Threads" tab to see what each thread is doing.

**Comment by axfelix** [comment]
I can no longer duplicate today! So that's a good sign that it may have been a strange, brief, network symptom. Closing for now.
