### ISSUE TITLE
Computing a hash from a binary resource

### ISSUE THREAD

**Issue by xatapult** [ndw/xmlcalabash1#274]
I cant get the p:hash step to work on a binary resource (on disk). What I do is this:

```xml
<p:hash match="hash" algorithm="sha" version="256">
    <p:input port="source">
      <p:inline>
        <root>
          <hash/>
        </root>
      </p:inline>
    </p:input>
    <p:with-option name="value" select="unparsed-text(some-binary-file)"/>
    <p:with-param name="null" select="()"/>
  </p:hash>
```

What happens is that I get the puzzling error message "input length = 1" which looks like a debug message left-over.

Some remarks about this:
- I'm not sure the above construction *should* actually work. The unparsed-text() function (as I read in in Michael Kay's XSLT 2 book) does not support control characters and of course a binary file will be full of them
- So it could be something in unparsed-text() instead of in p:hash
- If unparsed-text() is not the way to go, is there another  way to do this?

Running Calabash in the latest oXygen@20180524: 1.1.18-98

**Comment by ndw** [comment]
There's no way to get a string containing the contents of a binary file. Too many control characters are simply not allowed. I added a `p:hash-document` step to XML Calabash 1.1.21 that I believe will do what you need. Feel free to tell me I'm wrong, of course :smile:
