### ISSUE TITLE
Problem running latest Calabash release on Java 7

### ISSUE THREAD

**Issue by Conal-Tuohy** [ndw/xmlcalabash1#277]
I have recently upgraded an installation to the latest Calabash (1.1.21-98) and found that the distribution is now built to require Java 8.

NB the [documentation on running xmlcalabash](http://xmlcalabash.com/docs/reference/javasetup.html) still says "You must have Java 1.7 or later installed in order to run XML Calabash".

The [documentation for _building_ xmlcalabash](http://xmlcalabash.com/docs/reference/requirements.html) still lists the requirement: "Java 1.7 or later", which implies to me that the code doesn't use any specifically Java 8 features, in which case you should probably still be building the releases with a target version of 1.7. 

Specifically the error I see is:

java.lang.UnsupportedClassVersionError: org/xmlresolver/CatalogSource : Unsupported major.minor version 52.0 (unable to load class org.xmlresolver.CatalogSource)

If I open the class file I can verify the format is indeed version 52.0 (i.e. Java 8):
```
javap -verbose org/xmlresolver/CatalogSource.class | grep version
  minor version: 0
  major version: 52
```

**Comment by Conal-Tuohy** [comment]
Alternatively, maybe the answer is to just have a clear statement that Java 8 runtime is now required.

**Comment by ndw** [comment]
I believe that's a bug in the the resolver distribution that I fixed recently. I accidentally built that jar without specifying 1.7 class files. But it looks like I failed to update the dependency in the XML Calabash project :cry: 

Can you update your XML Resolver jar to 0.13.3 and tell me if that fixes the problem?

**Comment by Conal-Tuohy** [comment]
I have actually gone ahead and upgraded the platform to Java 8, since Java 7 is officially ancient anyway ;-)

**Comment by ndw** [comment]
Fair enough!
