### ISSUE TITLE
Semantics of assert-valid in p:validate-with-schematron

### ISSUE THREAD

**Issue by gimsieke** [ndw/xmlcalabash1#278]
A customer just wondered why a pipeline that uses `p:validate-with-schematron` behaves differently for two documents although each of them rises a Schematron error. Since we were only interested in the SVRL, I switched `assert-valid` to `false` and then both documents behaved the same. It turns out that in one of the reports, there was an `svrl:failed-assert` while the other one only contained an `svrl:successful-report`. Checking the [code](https://github.com/ndw/xmlcalabash1/blob/saxon98/src/main/java/com/xmlcalabash/library/ValidateWithSCH.java#L184) brought to light that you only check for failed-asserts, not for successful-reports. In my view they should be treated the same though, that is, in Schematron a successful report is a failed assertion. 
In any case, we should clarify in the 3.0 spec whether the presence of an `svrl:successful-report` is supposed to raise the same dynamic error as `svrl:failed-assert` when `assert-valid="true"`.

**Comment by ndw** [comment]
That's a bug. I'll fix it asap.

**Comment by ndw** [comment]
Fixed in 1.1.22.
