### ISSUE TITLE
Attributes @sequence and @kind should not be allowed on p:input in invocation of steps

### ISSUE THREAD

**Issue by raducoravu** [ndw/xmlcalabash1#279]
If I have an XProc like this:

        <p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
            <p:input port="source">
                <p:document href="document.xml"/>
            </p:input>
            <p:output port="result">
                <p:pipe step="checkReservedWords" port="result"/>
            </p:output>
            
            
            <p:validate-with-schematron phase="classificationValidation" name="checkClassifications">
                <p:input port="schema">
                    <p:document href="check-classifications-and-reserved-words.sch"/>
                </p:input>
                <p:input port="parameters" sequence="true" kind="document">
                    <p:empty/>
                </p:input>
            </p:validate-with-schematron>
            
            
            <p:validate-with-schematron phase="reservedWordValidation" name="checkReservedWords">
                <p:input port="source">
                    <p:pipe step="checkClassifications" port="result" />
                </p:input>
                <p:input port="schema">
                    <p:document href="check-classifications-and-reserved-words.sch"/>
                </p:input>
                <p:input port="parameters" sequence="true">
                    <p:empty/>
                </p:input>
            </p:validate-with-schematron>
            
        </p:declare-step>

you can create an XProcRuntime object and load the XProc in it without any error reported. But the usages of the @sequence and @kind attributes on the p:input elements should be flagged as errors.
Validating the XProc with the RNG schema flags the problems.

**Comment by raducoravu** [comment]
This was reported on:
https://www.oxygenxml.com/forum/viewtopic.php?f=1&t=16936&p=48654#p48654

**Comment by ndw** [comment]
Fixed in 1.1.22.
