### ISSUE TITLE
XAtomicStep doesn't give XPaths a static base URI

### ISSUE THREAD

**Issue by argv-minus-one** [ndw/xmlcalabash1#28]
Attempting to call `static-base-uri()` in an XPath on a pipeline element (in my case, a `<p:variable>`) yields the empty string, instead of the base URI of the pipeline element.

It looks like this is because `XAtomicStep.evaluateXPath` method does not call `xcomp.setBaseURI()`.

**Comment by ndw** [comment]
Fixed, I believe.
