### ISSUE TITLE
restlet.org maven repository does not exist anymore

### ISSUE THREAD

**Issue by cmarchand** [ndw/xmlcalabash1#280]
In maven `com.xmlcalabash:xmlcalabash:jar:1.1.20-98` artifact, `pom.xml` declares a repository for `https://maven.restlet.org`. According to [Restlet web site](https://restlet.com/), restlet has move to Talend, and domain extension is now `.com`.

Could you publish quickly a maintenance release, changing repository URL to `http://maven.restlet.com/`, as all projects that declare a dependency to com.xmlcalabash:xmlcalabash:jar:1.1.20-98 are not able to build successfully.

The workaround to this probvlem, is to declare a mirror in `settings.xml`
```
  <mirror>
    <id>restletMirror</id>
    <url>https://maven.restlet.com</url>
    <mirrorOf>restlet</mirrorOf>
  </mirror>
```
Thanks a lot

**Comment by ndw** [comment]
I just deleted all my maven and gradle cached restlet.org artifacts and rebuilt without any problems. Where are you seeing the difficulty?

**Comment by cmarchand** [comment]
Certificate is inconsistent. Try accessing from your web browser to [https://maven.restlet.org/](https://maven.restlet.org/), you should see the warning.
And maven is very reluctant to use sites where there are authentication issues...

**Comment by ndw** [comment]
I think that's it. Give a shout if you're still having trouble, @cmarchand
