### ISSUE TITLE
subresources for jar loaded pipelines do not load properly

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#29]
If you load a pipeline with a jar URI:

```
     pipeline = runtime.load(MyStuff.class.getResource("insert.xpl").toString());
```

any document pointed to by a <p:document href="..."/> won't load.  My expectation is the base URI is the jar URI and so those reference should resolve against the jar file as well.

By default, this does not work.  Somehow the base URI isn't resolving the relative reference and the system expects to find it relative to the current directory.

**Comment by ndw** [comment]
I don't see how toString() can return anything with with a base URI...

**Comment by ndw** [comment]
I just checked in a patch that might fix this. Can you give it a try and let me know?

**Comment by ndw** [comment]
Assuming fixed.
