### ISSUE TITLE
1.1.26-99: maven central deployment incomplete

### ISSUE THREAD

**Issue by thvitt** [ndw/xmlcalabash1#291]
For xmlcalabash 1.1.26-99, [only the .jar file appears at maven central](http://central.maven.org/maven2/com/xmlcalabash/xmlcalabash/1.1.26-99/), the .pom and the other artifacts are missing. As a consequence, dependency resolution does not work.

Both 1.1.25-99 and 1.1.26-98 seem to be ok.

**Comment by ndw** [comment]
Weird. Artifacts can't be changed after release, but 1.1.27 looks better. AFAICT.
