### ISSUE TITLE
1.2.0 zip file structure

### ISSUE THREAD

**Issue by AirQuick** [ndw/xmlcalabash1#302]
`xmlcalabash-*.jar` and `lib/` are not in https://github.com/ndw/xmlcalabash1/releases/download/1.2.0-99/xmlcalabash-1.2.0-99.zip.
Is it deliberate? Will XML Calabash zip file be released in this structure from 1.2.0 onward?

**Comment by ndw** [comment]
No, that's a bug. Sorry about that, a side effect of bungling about with Gradle, I'm sure. Will try to fix today.

**Comment by ndw** [comment]
Fixed in 1.2.1 released today.
