### ISSUE TITLE
p:directory-list fails at filenames with combining characters

### ISSUE THREAD

**Issue by mkraetke** [ndw/xmlcalabash1#308]
`p:directory-list` raises an XC0017 error when processing a file that contains combining characters in the filename.

```
zfsoz.2020.49.issue-1/zfsoz-2020-0005/suppl/Hägglund-Lörz-Studienfachwahl-Onlineanhang.pdf
```
For example, the letter `ä` is constructed with `a (#x61)` and ` ̈ (#x308)`.

[Here is the sample file](https://github.com/ndw/xmlcalabash1/files/4764705/zfsoz_zfsoz.2020.49.issue-1_2020-06-02--13-27-00.zip)

I've tested on Windows 10.

**Comment by ndw** [comment]
I can't even create that file on the Mac. The only way that `XC0017` arises in `p:directory-list` is if the Java system returns `FileNotFoundException`. I don't think there's anything I can do about that. :-(

**Comment by mkraetke** [comment]
OK, thank you! Then I'll wrap this in a p:try.
