### ISSUE TITLE
missing release release artifact in the latest release (1.2.1-100b1)

### ISSUE THREAD

**Issue by chenrui333** [ndw/xmlcalabash1#310]
Compare between the two releases [1.2.1-99](https://github.com/ndw/xmlcalabash1/releases/tag/1.2.1-99) and [1.2.1-100b1](https://github.com/ndw/xmlcalabash1/releases/tag/1.2.1-100b1). I found the release artifacts missing the latest release.

**Comment by chenrui333** [comment]
cc @ndw

**Comment by ndw** [comment]
Yes. Sorry. I failed to tag 100b1 (presumably because I intended it as some kind of beta release) and so the build artifacts weren't included. I'll build 100 now.

**Comment by chenrui333** [comment]
Thank you!

**Comment by ndw** [comment]
This will probably have to be finished tomorrow, I have some dependency issues that I have to let settle.

**Comment by ndw** [comment]
I believe that 1.2.3-99 and 1.2.3-100 are both released. They should appear on Maven soon.

(I abandoned 1.2.2 because I messed up the build versioning.)
