### ISSUE TITLE
add cdata-section-elements serialization results in calabash not executing the pipeline

### ISSUE THREAD

**Issue by mkraetke** [ndw/xmlcalabash1#323]
Hi @ndw,

I've added `@cdata-section-elements` to `<p:serialization>` but Calabash just prints the standard usage information instead of executing the pipeline. The [Calabash download pages](https://xmlcalabash.com/download/) states that `cdata-section-elements` are supported since version 0.9.11. Here is a minimal pipeline which demonstrates the issue:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
  xmlns:c="http://www.w3.org/ns/xproc-step" 
  version="1.0">
  
  <p:input port="source">
    <p:inline>
      <doc>
        <tex-math>\cos (2\theta) = \cos^2 \theta - \sin^2 \theta</tex-math>
      </doc>
    </p:inline>
  </p:input>
  
  <p:output port="result"/>
  
  <p:serialization port="result" cdata-section-elements="tex-math"/>
  
  <p:identity/>
  
</p:declare-step>
```

This is not an urgent issue, I have an XSLT-based workaround.

best, Martin

**Comment by ndw** [comment]
Either that's a lie or I broke it at some point after that. Man, those pages are out of date! Anyway, I have a fix and will republish this weekend.

**Comment by mkraetke** [comment]
Thank you!
