### ISSUE TITLE
1.3.2-99: xsl:message not printed

### ISSUE THREAD

**Issue by AirQuick** [ndw/xmlcalabash1#324]
With 1.3.1 (`xmlcalabash-1.3.1-99.zip`) or earlier, messages from `xsl:message` were printed.
With 1.3.2-99 (`xmlcalabash-1.3.2-99.zip`), messages are not printed. Is it no longer supported out-of-the-box?

```console
$ cat pipe.xpl 
<?xml version="1.0"?>
<p:declare-step version="1.0" xmlns:p="http://www.w3.org/ns/xproc">
  <p:input port="source">
    <p:empty />
  </p:input>
  <p:output port="result" />
  <p:xslt>
    <p:input port="source">
      <p:inline>
        <doc />
      </p:inline>
    </p:input>
    <p:input port="stylesheet">
      <p:inline>
        <xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
          <xsl:template match="doc">
            <xsl:message select="'my message'" />
          </xsl:template>
        </xsl:stylesheet>
      </p:inline>
    </p:input>
    <p:input port="parameters">
      <p:empty />
    </p:input>
  </p:xslt>
</p:declare-step>
$ java -jar xmlcalabash-1.3.1-99/xmlcalabash-1.3.1-99.jar pipe.xpl
INFO : pipe.xpl:7:11:my message

        
      
$ java -jar xmlcalabash-1.3.2-99/xmlcalabash-1.3.2-99.jar pipe.xpl 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

        
      
$ 
```

**Comment by ndw** [comment]
This is a damned-if-I-do, damned-if-I-don't situation and I really don't know what the right answer is. If you put one of the concrete logging back ends on your class path (e.g., `slf4j-simple`), you'll get the logging messages. If I ship XML Calabash with that back end built in, it's harder for users in other environments to work around it.

**Comment by AirQuick** [comment]
Thanks. Adding `log4j-api-2.14.1.jar`, `log4j-core-2.14.1.jar` and `log4j-slf4j-impl-2.14.1.jar` to the class path restored the message print. That's a bit inconvenient, but I'll do that for 1.3.2 and onward.
