### ISSUE TITLE
import de.undercouch.gradle.tasks.download.Download

### ISSUE THREAD

**Issue by imuralice** [ndw/xmlcalabash1#327]
I am facing an error at this line "import de.undercouch.gradle.tasks.download.Download" in download-models.gradle file. Please can anyone help me solve this?

Build.Project:
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }
}

**Comment by ndw** [comment]
There's no `download-models.gradle` file in this project. Are you sure you posted this bug to the correct repository?

In any event, I don't see the error in what you posted. Can you show us the output from running `gradle` (or preferably `./gradlew` if it exists)
