### ISSUE TITLE
Calabash error: Unsupported HTML version: 1.0

### ISSUE THREAD

**Issue by ttasovac** [ndw/xmlcalabash1#344]
My source documents are XHTML 1.0 Transitional, and I'm planning to do a bunch of XSLT transformations with them. The first XSLT transformation works on its own, but when I put it in my xproc pipeline, oXygen gives me the Calabash error

`Unsupported HTML version: 1.0`

What does that mean? Why should calabash care about which HTML version I'm using, when Saxon doesn't. After all, Calabash is not doing the actual transformation, right?

Is there a way around this? I'll be most grateful for any pointers.

**Comment by ndw** [comment]
Can you provide a test case? My guess is that you have a stylesheet that specifies

```
<xsl:output method="html" version="1.0"/>
```

Or a pipeline that does the same thing with serialization options. For XHTML 1.0, I'd try the xml serialization method.

**Comment by ttasovac** [comment]
You were absolutely right —  the problem was with the serialization option in the pipeline. I had `method="html"` which, I just learned, is interpreted by default as version 1.0; adding `version="4.0"`  or simply going with `method="xml"` gets rid of the error. Many thanks for the pointer!
