### ISSUE TITLE
NullPointerException in com.xmlcalabash.util.XProcURIResolver

### ISSUE THREAD

**Issue by raducoravu** [ndw/xmlcalabash1#35]
I have an XProc with code like this:
.................
    &lt;p:xsl-formatter content-type=&quot;application/pdf&quot;&gt;
        &lt;p:with-option name=&quot;href&quot; select=&quot;$pdf-file&quot;&gt;&lt;/p:with-option&gt;
        &lt;p:with-param name=&quot;UserConfig&quot; select=&quot;$fop-config&quot;/&gt;
    &lt;/p:xsl-formatter&gt;
...................

which tries to generate PDF using Apache FOP.

The FOP configuration file looks like this:

&lt;fop version=&quot;1.0&quot;&gt;
    &lt;accessibility&gt;true&lt;/accessibility&gt;
    &lt;target-resolution&gt;240&lt;/target-resolution&gt;
    &lt;renderers&gt;
        &lt;renderer mime=&quot;application/pdf&quot;&gt;
            &lt;fonts&gt;
                &lt;auto-detect/&gt;
            &lt;/fonts&gt;
        &lt;/renderer&gt;
    &lt;/renderers&gt;
&lt;/fop&gt;

When transforming, the output fails with a message like:

Failed to process FO document with FOP null

which is actually generated by:

Caused by: java.lang.NullPointerException
    at java.net.URI$Parser.parse(Unknown Source)
    at java.net.URI.<init>(Unknown Source)
    at com.xmlcalabash.util.XProcURIResolver.resolve(Unknown Source)
    at org.apache.fop.apps.FOURIResolver.resolve(FOURIResolver.java:179)
    at org.apache.fop.apps.FopFactory.resolveURI(FopFactory.java:753)
    at org.apache.fop.apps.FOUserAgent.resolveURI(FOUserAgent.java:425)
    at org.apache.fop.render.DefaultFontResolver.resolve(DefaultFontResolver.java:44)
    at org.apache.fop.fonts.FontLoader.openFontUri(FontLoader.java:154)
    at org.apache.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:94)
    at org.apache.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:84)
    at org.apache.fop.fonts.FontLoader.getFont(FontLoader.java:190)
    at org.apache.fop.fonts.FontLoader.loadFont(FontLoader.java:139)
    at org.apache.fop.fonts.LazyFont.load(LazyFont.java:134)
    at org.apache.fop.fonts.LazyFont.getAscender(LazyFont.java:241)
    at org.apache.fop.fonts.Font.getAscender(Font.java:106)
    at org.apache.fop.layoutmgr.BlockLayoutManager.initialize(BlockLayoutManager.java:87)
    at org.apache.fop.layoutmgr.AbstractLayoutManager.getChildLM(AbstractLayoutManager.java

So the method:

public Source resolve(String href, String base) throws TransformerException {

receives a NULL base from Apache FOP and tries to make an URI out of it:

URIResolver(file:/C:/Windows/FONTS/arial.ttf,null)

So you should take into account on the URIResolver the possibility of a NULL base.

The workaround is simple, a "<font-base>./</font-base>" can be specified in the configuration file in order for Apache FOP to also specify the base in the URI resolver and avoid the NPE.

One more improvement which would help debug such cases would be that in the method:

com.xmlcalabash.library.XSLFormatter.run()

when an exception is caught, it should not be ignored but instead be provided as the cause of the thrown XProcException.

**Comment by ndw** [comment]
I believe XSLFormatter.run does include the underlying exception:

```
        try {
            out = new BufferedOutputStream(new FileOutputStream(output));
            provider.format(source.read(),out,contentType);
        } catch (XProcException e) {
            throw e;
        } catch (Exception e) {
            throw new XProcException(step.getNode(), "Failed to process FO document", e);
        } finally {
            out.close();
        }
```

If you can provide a complete pipeline that demonstrates the NPE problem, I'll see what I can do.

I'm not sure what the right semantic is when the base is null.

**Comment by raducoravu** [comment]
Hi Norm, 

About wrapping the original exception, I was referring to this part of the XSLFormatter:

```
    FoProcessor provider = null;
    for (String className : foClasses) {
        if (provider == null) {
            try {
                provider = (FoProcessor) Class.forName(className).newInstance();
                provider.initialize(runtime,step,options);
            } catch (NoClassDefFoundError ncdfe) {
                provider = null;
            } catch (Exception e) {
              //THE NPE IS CAUGHT HERE...........................
                provider = null;
            }
        }
    }

    if (provider == null) {
        throw new XProcException(step.getNode(), "Failed to instantiate FO provider");
    }
```

About the approach in the XProcURIResolver when the base is NULL, the Xerces URI Resolver has the code something like:
.....
  if (base==null) {
    url = new URL(uri);
    result = url.toString();
  } else {
    URL baseURL = new URL(base);
    url = (href.length()==0 ? baseURL : new URL(baseURL, uri));
    result = url.toString();
  }
....

Regards,
Radu

**Comment by ndw** [comment]
Ah. Ok. I'd already reworked part of that code in XSLFormatter which partially corrected the problem. I improved it some more :-)

And I attempted to do the Xerces compatible thing in resolve()

**Comment by raducoravu** [comment]
Thanks, Norm.

**Comment by ndw** [comment]
I hope this is fixed now. Please reopen if it isn't.
