### ISSUE TITLE
Extension step library is no more available

### ISSUE THREAD

**Issue by nkutsche** [ndw/xmlcalabash1#353]
Because @ndw is reworking his page, the URL `http://xmlcalabash.com/extension/steps/library-1.0.xpl` returns `404`.

The new URL would be `http://xmlcalabash.com/archive-1.x/extension/steps/library-1.0.xpl`. But since I assume there are hundreds of XProc scripts using this URL, I would strongly recommend to restore the old URL.

**Comment by ndw** [comment]
Does this cause an actual pipeline to fail? That's supposed to be a magic URI that the processor doesn't need to retreive

But I will put it back.

**Comment by nkutsche** [comment]
Yeah, it seems that I'm not at the end of my debugging road. My pipeline suddenly fails and I thought that this is the reason. But meanwhile I found out that other pipelines with the same include statements are not failing.

Actually I thought that calabash contains a catalog to redirect this URL - but I can't find this catalog anymore.

**Comment by ndw** [comment]
That URI is just built in magic, no catalog required. But in any event `/extension/steps` is back on the website.

**Comment by ndw** [comment]
I'm going to close this, I think it's as fixed as I can make it. But don't hesitate to open another bug if I've messed something else up 😦

**Comment by nkutsche** [comment]
Yes, this can be closed. Thank's for the fast response!

**Comment by nkutsche** [comment]
Ok, my issue had multiple levels. One of it was that I'm using [XProcSpec](https://github.com/daisy/xprocspec/) and that is [trying to load each imported XProc file](https://github.com/daisy/xprocspec/blob/release/1.4.3/src/main/resources/content/xml/xproc/preprocess/preprocess.xpl#L176) using `p:load`. Calabash does the magic only for the `p:import` - not if you try to load `<p:load href="http://xmlcalabash.com/extension/steps/library-1.0.xpl"/>`. But that is ok, I think.
