### ISSUE TITLE
"test" option problem in p:split-sequence

### ISSUE THREAD

**Issue by l9lk** [ndw/xmlcalabash1#36]
Hi
I think there is design bug in  "computeValue" method of "XAtomicStep". On the 551 line You check if there is more documents in the pipe and if so, exception is thrown "More than one document in context for parameter...". This prevents SplitSequence class to run.

There is also another issue here. The xpath expression is evaluated first in XAtomicStep.computeValue method and so the result of this evaluation is passed to the run method of SplitSequence class. In order to properly evaluate test expression in  SplitSequence you have to wrap it in additional quotes.
Should it be like that?

XProc recomendation in 2.6 says:

> XPath expressions are also passed to some steps. These expressions are evaluated by the implementations of the individual steps.

and further:

> The XPath expression “@role='chapter'” is passed literally to the test option on the p:split-sequence step. That's because the nature of the p:split-sequence is that it evaluates the expression. Only some options on some steps expect XPath expressions.

**Comment by ndw** [comment]
There are split sequence tests in the test suite and I pass those. Can you post a small example pipeline that demonstrates the problem.

**Comment by l9lk** [comment]
I did some testing and was able to narrow down the problem. It arises only when there are active bindings.I slightly modified your second test and the exception is thrown:

``` xml
<p:pipeline xmlns:t="http://xproc.org/ns/testsuite" xmlns:p="http://www.w3.org/ns/xproc" xmlns:c="http://www.w3.org/ns/xproc-step" xmlns:err="http://www.w3.org/ns/xproc-error" version="1.0" name="pipeline">

<p:identity>
    <p:input port="source" sequence="true">
        <p:pipe step="pipeline" port="source"/>
        <p:inline><ex:stylesheet xmlns:ex="http://example.com/ex"/></p:inline>
        <p:pipe step="pipeline" port="source"/>
        <p:inline><ex:stylesheet xmlns:ex="http://example.com/ex"/></p:inline>
    </p:input>
</p:identity>


<p:split-sequence>
  <p:with-option xmlns:ex2="http://example.com/ex" name="test" select="'/ex2:*'"/>
</p:split-sequence>

<p:count/>

</p:pipeline>
```

**Comment by ndw** [comment]
Thanks. I'll take a closer look asap.

**Comment by ndw** [comment]
Ah. This isn't an implementation bug, it's a consequence of XProc language design that's a little painful here.

p:with-option gets the context from the default readable port, on which a sequence appears, and that's an error.

But in this case, you don't need any context to "compute" the literal string. Two options:
1. Put the test right on the split-sequence:

```
    <p:split-sequence xmlns:ex2="http://example.com/ex"
                      test="/ex2:*"/>
```
1. Make the context explicit in the with-option:

```
     <p:with-option xmlns:ex2="http://example.com/ex" name="test" select="'/ex2:*'">
       <p:empty/>
     </p:with-option>
```

Hope that helps. And sorry for the delay.
