### ISSUE TITLE
Xinclude not working…?

### ISSUE THREAD

**Issue by Zearin** [ndw/xmlcalabash1#38]
# Desperate and in Despair

Please help me? ☺  I am at that place we’ve all been before, where the simplest thing refuses to work…and…I am about to go bats**t crazy at this point.  

I am attempting to use a pipeline with _a single XInclude step_.  And it’s failing.  

I don’t mean that I get errors—I mean the XInclude just _doesn’t happen_.  And I have spent the past 3½ hours trying to figure out why without luck.  I cannot believe I’ve already wasted so much time on what is considered a fundamental building block of anything to do with anything in XML.  

---

I don’t know if the issue is with Calabash, or Saxon, or what.  But I have tried running the pipeline both from the command line and from within Oxygen, with the same results: XIncludes are not processed, no errors are emitted, and the markup or the XIncludes themselves is just copied to the output.  

So, sorry if this is an inappropriate channel to ask for help. ☹  I don’t really know, because I can’t even begin to narrow the problem down.  But I’ll gladly e-hug (or promise not to) any help offered, just the same!

---
### Input Document:

``` xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:xi="http://www.w3.org/2003/XInclude"
    xml:lang="en-us"
    lang="en-us">

    <head>
        <title>Untitled</title>

        <link rel="stylesheet" type="text/css" href="_css/index.css" />
    </head>

    <body>

        <xi:include parse="xml" href="_includes/header.xhtml">
            <xi:fallback> ERROR </xi:fallback>
        </xi:include>

        <div id="content">
        ... 
        </div>

        <xi:include parse="xml" href="_includes/footer.xhtml">
            <xi:fallback> ERROR </xi:fallback>
        </xi:include>

    </body>
</html>
```
### Pipeline

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<p:declare-step
    name        =   "xinc"

    version     =   "1.0"
    xpath-version=  "2.0"

    xmlns:p     =   "http://www.w3.org/ns/xproc"
    xmlns:c     =   "http://www.w3.org/ns/xproc-step"
    xmlns:err   =   "http://www.w3.org/ns/xproc-error"
    xmlns:xs    =   "http://www.w3.org/2001/XMLSchema"

    xmlns:pos   =   "http://exproc.org/proposed/steps/os"
    xmlns:pxf   =   "http://exproc.org/proposed/steps/file"
    xmlns:pxfn  =   "http://exproc.org/proposed/functions"
    xmlns:pxp   =   "http://exproc.org/proposed/steps"

    xmlns:cx    =   "http://xmlcalabash.com/ns/extensions"
    xmlns:cxf   =   "http://xmlcalabash.com/ns/extensions/fileutils"
    xmlns:cxo   =   "http://xmlcalabash.com/ns/extensions/osutils"
    xmlns:cxu   =   "http://xmlcalabash.com/ns/extensions/xmlunit"

    xmlns:h     =   "http://www.w3.org/1999/xhtml/"
    xmlns:xsl   =   "http://www.w3.org/1999/XSL/Transform"
    xmlns:xi    =   "http://www.w3.org/2003/XInclude"

    xmlns:local =   "#empty">



    <p:documentation>
        <h:p>Performs simple XIncludes.</h:p>
    </p:documentation>



    <!--    
        I/O
    ======================================================================== -->
    <p:input    port="source" kind="document"   />
    <p:output   port="result"
                primary="true"  />

    <!--    
        SERIALIZATIONS 
        May bind to any output (not just "result").
    ======================================================================== -->
    <p:serialization   port    ="result" 

        doctype-system         ="about:legacy-compat"
        encoding               ="UTF-8" 
        indent                 ="true"
        media-type             ="xml" 
        method                 ="xml"
        omit-xml-declaration   ="false" 
        version                ="1.0"
    />


    <!--    
        MAIN PIPELINE CONTENT
    ======================================================================== -->
    <p:xinclude />



</p:declare-step>
```
### Output

This is copied from my command-line attempt; Oxygen attempts have the same result (except for the `Failed to obtain EE processor` at the beginning, which shouldn’t matter for XInclude anyway).

``` xml

Failed to obtain EE processor; using HE instead.
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xi="http://www.w3.org/2003/XInclude" xml:lang="en-us" lang="en-us">

    <head>
        <title>Untitled</title>

        <link rel="stylesheet" type="text/css" href="_css/index.css"/>
    </head>

    <body>

        <xi:include parse="xml" href="_includes/header.xhtml">
            <xi:fallback> ERROR </xi:fallback>
        </xi:include>

        <div id="content">
        ... 
    </div>

        <xi:include parse="xml" href="_includes/footer.xhtml">
            <xi:fallback> ERROR </xi:fallback>
        </xi:include>

    </body>
</html>

```
### Version Info

```
$ calabash -v
XML Calabash version 1.0.2 (for Saxon 9.4.x), an XProc processor
```

```
$ saxon -versionmsg
No source file name
Saxon-HE 9.4.0.2J from Saxonica
```

**Comment by l9lk** [comment]
I haven't tested it, but probably you used wrong namespace for xi. Calabash uses http://www.w3c.org/2001/Xinclude.
Hope this helps.

**Comment by Zearin** [comment]
Oh.  My.  God.  

That did it!  Thank you SO much @l9lk!  :D  

I can’t believe that’s what the problem was.  Why are there two namespaces for XInclude?!

**Comment by l9lk** [comment]
I think there is only one. W3c recommendation states:

> XInclude defines a namespace associated with the URI http://www.w3.org/2001/XInclude. The XInclude namespace contains two elements with the local names include and fallback. For convenience, within this specification these elements are referred to as xi:include and xi:fallback respectively.

**Comment by ndw** [comment]
Glad you got it working!

**Comment by kaycebasques** [comment]
I too was on the point of meltdown because of this exact same problem. 

I'll verbosely recount my experiences for any other lost souls experiencing similar symptoms.

If you're running Saxon from the command line using the Java platform and the -xi option is silently failing, it could be because your xi:include directives contain the wrong namespace for xi. The correct namespace is "http://www.w3.org/2001/XInclude", not "http://www.w3.org/2003/XInclude". 

When invoking Saxon with the basic command: 
java -jar saxon9he.jar -xi -s:src.xml -xsl:transform.xsl -o:page.xml

The following XInclude will fail:

```
<?xml version="1.0"?>
<webpage>
<body>Hello world!</body>
   <xi:include href="footer.xml" xmlns:xi="http://www.w3.org/2003/XInclude"/>
</webpage>
```

Whereas the following XInclude will succeed.

```
<?xml version="1.0"?>
<webpage>
<body>Hello world!</body>
   <xi:include href="footer.xml" xmlns:xi="http://www.w3.org/2001/XInclude"/>
</webpage>
```

If I recall correctly, the Java flavor of Saxon is not processing the XInclude instruction: by default Saxon uses the Apache Xerces XML Parser that comes bundled in the JDK.  So it's not Saxon per se that is "failing", it's the Apache Xerces XML Parser that Saxon invokes which requires the xi namespace of "http://www.w3.org/2001/XInclude".
