### ISSUE TITLE
XMLResolver not using stylesheet location to resolve relative urls

### ISSUE THREAD

**Issue by volodymyr-mykhailyk** [ndw/xmlcalabash1#43]
Not sure if this belongs to current project. However when I am using your XMLResolver with Calabash during resolving of imports current working directory is used as base path instead of xsl location.
For example:
current working dir is: 'C:/projects/dita.project'
pipeline calling xsl using relative path: 'hlp/hlp.xsl'
hlp.xsl contain import with path '../common/common-functions.xsl'

during execution of such pipeline I am getting following exception:

``` text
SEVERE: 12:err:XTSE0165:I/O error reported by XML parser processing 
file:/C:/projects/common/common-functions.xsl: C:\projects\common\common-functions.xsl 
(The system cannot find the path specified)
```

It is starting relative path from current working dir instead of xsl location

**Comment by ndw** [comment]
That is odd. I'll take a look. Can you send a small test case that demonstrates the problem?

**Comment by volodymyr-mykhailyk** [comment]
Unfortunatly no. I've gave up with trying to use Calabash and removed all tests because it wasn't compatible with our requiremnts about processing pipeline.

**Comment by ndw** [comment]
Well, that's too bad.
