### ISSUE TITLE
Jing validation: Error loading schema

### ISSUE THREAD

**Issue by rdeltour** [ndw/xmlcalabash1#51]
I have a small XProc document that validates a document with a RelaxNG schema loaded from a `p:document` with a relative URI. The schema has an `include` element that references another schema file sitting in the same directory. When I invoke Calabash with no URI Resolve it runs fine, but it crashed with "SEVERE: com.xmlcalabash.core.XProcException: Error loading schema" when I set a URI Resolver like this:

`calabash -U org.xmlresolver.Resolver test.xpl`

I'll attach the samples to reproduce.

I tried to debug Calabash, and it seems Jing fails to parse the schema, complaining at some point that the "namespace URI of document element must be "http://relaxng.org/ns/structure/1.0"". I'm clueless.

**Comment by rdeltour** [comment]
Repro files are available there:
https://gist.github.com/3018018

**Comment by ndw** [comment]
I think this is dependent on https://code.google.com/p/jing-trang/issues/detail?id=167

**Comment by ndw** [comment]
Wow. That was ugly. Deep in the XProcURIResolver, I managed to create an XMLReader that wasn't namespace aware. Fixed now for 1.0.7.

**Comment by rdeltour** [comment]
Great, good catch.
