### ISSUE TITLE
ThreadLocal use produces memory leaks in pooled environments

### ISSUE THREAD

**Issue by capitancambio** [ndw/xmlcalabash1#54]
Hi,

In several classes the XProcRuntime object is stored in ThreadLocal variables. This leads to important memory leaks when calabash is used within a ThreadPool (as the objects are never collected by the GC). I reckon that the cleanest way is solve this issue is to wrap these objects around a WeakReference.

I've got the modified classes (src/com/xmlcalabash/functions/*) under a local branch that I could push if you wish.  

Even doing that the memory leak persists as Saxon stores the XProcRuntime object in another ThreadLocal as shown in this trace:
com.xmlcalabash.core.XProcRuntime  
runtime of com.xmlcalabash.util.XProcURIResolver 
uriResolver of net.sf.saxon.Configuration  
notationSet of net.sf.saxon.lib.ConversionRules  
conversionRules of net.sf.saxon.type.StringConverter$StringToAnyURI  
value of java.util.LinkedHashMap$Entry  
[62] of java.util.HashMap$Entry[64]  
table of net.sf.saxon.expr.sort.LRUCache$1  
map of net.sf.saxon.expr.sort.LRUCache  
value of java.lang.ThreadLocal$ThreadLocalMap$Entry
[105] of java.lang.ThreadLocal$ThreadLocalMap$Entry[128]
table of java.lang.ThreadLocal$ThreadLocalMap
threadLocals of java.lang.Thread [Stack Local]

Thanks

**Comment by ndw** [comment]
This was fixed in 1.0.5, I believe.
