### ISSUE TITLE
<cx:eval> doesn't work (NPE, other weird errors)

### ISSUE THREAD

**Issue by argv-minus-one** [ndw/xmlcalabash1#56]
With Calabash 1.0.3 (for Saxon-HE 9.4.0.2), I get a `NullPointerException` when trying to use `<cx:eval>`, and some _really_ strange errors if I fix the NPE.

In my test case, I have two files, named `pipe1.xpl` and `pipe2.xpl`, containing:

`pipe1.xpl`:

``` xml
<p:library xmlns:p="http://www.w3.org/ns/xproc" version="1.0" xmlns:test="http://example.com/">
        <p:pipeline type="test:pipe1" name="pipe-1">
                <p:identity/>
        </p:pipeline>
</p:library>
```

`pipe2.xpl`:

``` xml
<p:pipeline xmlns:p="http://www.w3.org/ns/xproc" version="1.0" xmlns:test="http://example.com/" xmlns:cx="http://xmlcalabash.com/ns/extensions">
        <p:import href="http://xmlcalabash.com/extension/steps/library-1.0.xpl"/>

        <cx:eval step="test:pipe1">
                <p:input port="pipeline">
                        <p:document href="pipe1.xpl"/>
                </p:input>
                <p:input port="options">
                        <p:empty/>
                </p:input>
        </cx:eval>
</p:pipeline>
```

This yields:

```
Sep 30, 2012 1:04:14 AM com.xmlcalabash.drivers.Main error
SEVERE: Pipeline failed: java.lang.NullPointerException
```

The problem is that `XProcRuntime.xprocData` doesn't get copied by `XProcRuntime`'s copy constructor. If I fix it just by adding `xprocData = runtime.xprocData;` to said constructor, though, I then get this stuff instead:

```
Sep 30, 2012 1:06:07 AM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: pipe1.xpl:2:46:Declared step has no subpipeline, but is not known.
Sep 30, 2012 1:06:07 AM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: No in-scope binding for source on XML-CALABASH-GENERATED-WRAPPER-PIPELINE
Sep 30, 2012 1:06:07 AM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: No in-scope binding for source on XML-CALABASH-GENERATED-WRAPPER-PIPELINE
Sep 30, 2012 1:06:07 AM com.xmlcalabash.drivers.Main error
SEVERE: com.xmlcalabash.core.XProcException: No in-scope binding for source on XML-CALABASH-GENERATED-WRAPPER-PIPELINE
```

Yikes. That looks like some kind of bug, hence this report.

I ran into this problem while trying to drive Calabash programmatically. I had been trying to get and run an `XPipeline` from its enclosing `XLibrary`, and got the error about "declared step has no subpipeline". At first, I thought I must have been doing something wrong, but then I found that `<cx:eval>` does the same thing and has the same problem…

**Comment by ndw** [comment]
Indeed. That was subtle. Fixed, I think. Trying to get the test suite passing again before pushing...

**Comment by ndw** [comment]
The test suite passes again, so I'm calling this fixed.
