### ISSUE TITLE
Feature suggestion: add support for gzip 

### ISSUE THREAD

**Issue by j-maly** [ndw/xmlcalabash1#58]
EXProc already adds support for ZIP files (http://exproc.org/proposed/steps/other.html#zip).

I have to deal with XML files that are publicly available on the web as gzip archives. It would be great if it were possible to work with the archives as a step in the pipeline - via a pair of steps pxp:gzip and pxp:ungzip similar to the pxp:zip and pxp:unzip steps.

**Comment by ndw** [comment]
On casual inspection, that looks straightforward.

**Comment by ndw** [comment]
I added support for pxp:compress and pxp:uncompress as documented on exproc.org. They're in the saxon94 branch now and will be in 1.0.7.
