### ISSUE TITLE
wrong exit-status

### ISSUE THREAD

**Issue by ruv** [ndw/xmlcalabash1#63]
When a pipeline terminated via xsl:message the exit-status is 0  (Calabash 1.0.3-94). 
Expected result: the exit-status must be non-zero.

I wonder is the exit-status (exit-code) always 0 in Calabash?

**Comment by ndw** [comment]
Ok, I changed the main driver so that it will exit with a non-0 status if the pipeline fails due to an exception (which xsl:message raises).
