### ISSUE TITLE
Being able to choose which configuration files are loaded

### ISSUE THREAD

**Issue by capitancambio** [ndw/xmlcalabash1#64]
Dear Norman,
We are trying to build a system based on calabash. We noticed that when the user has a custom .calabash in their home directory it clashes with our configuration files. In order to solve this I've introduced three system properties which are checked before loading the jar config fle, the home config file and the cwd cofig file.
com.xmlcalabash.config.home
com.xmlcalabash.config.jar
com.xmlcalabash.config.cwd
A pull request is being submitted in case you're interested in adding this feature.

Thanks.

**Comment by ndw** [comment]
Flags to suppress the `~/.calabash` and `./.calabash` configuration files seem reasonable, I guess. Though I'm tempted to make properties that contain the names of the files. So, maybe `com.xmlcalabash.config.user` which defaults to `~/.calabash` if it isn't set and `com.xmlcalabash.config.local` which defaults to `./.calabash`. Setting them to the empty string would suppress them.

I'm a little surprised by the requirement to be able to suppress the configuration file from the jar. Do you need to specify an alternate configuration? If you don't load something, you won't have implementations for any of the steps!

**Comment by capitancambio** [comment]
Thanks for the reply. Having both ~/.calabash and ./.calabash as you described is exactly what we were looking for . I don't have a strong point of view regarding the configuration file from the jar, it's true that you need all the declarations for steps, but they can be also feed from another configuration file or dynamically allowing clients of calabash gain more control over the internals. Anyway, that's beside the point of the reason of the patch ... 
thanks a million

**Comment by ndw** [comment]
There you go! :-)

**Comment by capitancambio** [comment]
:) greats!
