### ISSUE TITLE
Make sure the architecture supports a single XProcRuntime that can run multiple pipelines

### ISSUE THREAD

**Issue by ndw** [ndw/xmlcalabash1#74]
That means, for example, the profiling stuff needs to be moved off the runtime object.

The episode probably should be moved too.

**Comment by ndw** [comment]
That's silly. The XProcRuntime is the dynamic context.

Consider creating a "processor" level object that spawns XProcRuntimes.

**Comment by ndw** [comment]
I've completely redesigned the architecture for V2.0. I'm unlikely to pursue this in the 1.x version.

**Comment by fgeorges** [comment]
Do you mean the 2.0 architecture has a model "processor / compiled pipeline / runtime pipeline" ?

**Comment by ndw** [comment]
Yes.

**Comment by fgeorges** [comment]
Excellent :-)
