### ISSUE TITLE
URI resolver, XProcProcessor and XProcRuntime

### ISSUE THREAD

**Issue by fgeorges** [ndw/xmlcalabash1#77]
It is not possible to set the URI resolver to use for compilation, through the configurer.

When the XProcProcessor (let's say PROC) is constructed, it constructs a new configurer, then set the URI resolver.  Regardless it has been set or not.  So the configurer can't set the URI resolver on PROC in the constructor.  When PROC constructs a new XProcRuntime (let's say RUN), it is inherited PROC's resolver (which is not a specific one, because we can't set it).  Then it is called load(), which in turn calls configurer.configRuntime() right before compilation, but there is no setURIResolver() anymore on RUN, so the configurer once again can't set its own resolver.

Solution: probably, moving the block instantiating the configurer (in PROC) right below the one assigning a value to URI resolver (and right before the saxon config setting) would solve the problem.  If the custom resolver has to delegate at some point to the standard one, it can do so; if it needs to completely overrides it, it can also.

**Comment by fgeorges** [comment]
(sorry, failed to mention this is in the 1.1 branch)

**Comment by ndw** [comment]
Fixed by issue #88
