### ISSUE TITLE
Runtime object can be null when reporting error

### ISSUE THREAD

**Issue by fgeorges** [ndw/xmlcalabash1#79]
In drivers.Main, line 488, I added a check for runtime != null (in addition to instream != null).  I think this happens if an error occurs during compilation so runtime is null.  There is probably another way to parse instream, it is probably wrong to call runtime.parse has the input is a stream and does not have to pass through the runtime's URI resolver.

**Comment by fgeorges** [comment]
(sorry, once again failed to mention branch 1.1)

**Comment by ndw** [comment]
Fixed, I believe.
