### ISSUE TITLE
OutOfMemory issue with RelaxNG validation

### ISSUE THREAD

**Issue by rdeltour** [ndw/xmlcalabash1#83]
Calabash runs out of memory when a RelaxNG validation reports many errors (my limit seems to be around 3000 errors, running with latest sources on my default environment).

A repro pipeline can be found there:
https://gist.github.com/rdeltour/5107452

I'm not sure if there is a mem leak somewhere or if this is a legitimate limit. Calumet seems to cope well with a similar scenario.

Anyway, the issue seems to be related to storing all the error docs in memory in the XTry class; I don't think it is specific to the RelaxNG step.

**Comment by rdeltour** [comment]
Should be fixed with #84

**Comment by ndw** [comment]
Reopen if it's not fixed by #84, please.
