### ISSUE TITLE
Exception to use in an extension step

### ISSUE THREAD

**Issue by fgeorges** [ndw/xmlcalabash1#95]
`XProcRunnable.run()` can throw a `SaxonApiException`.  When writing an extension step, I guess this is not the correct exception to throw.  Maybe I missed something, but shouldn't there be a `StepException` or `XProcException` to use here?

**Comment by ndw** [comment]
SaxonApiException is a checked exception. You have to declare that it can be thrown. XProcExceptions aren't checked. You can, and should, throw and XProcException of there's a step error. I suppose a StepException could be invented, I think I'd resist making it a checked exception though.

**Comment by fgeorges** [comment]
OK.  It sounds rather weird to me to use non-checked exceptions in an API, but at least there is something :-)  Maybe it would make it more clear to add `XProcException` to the list of exceptions that can be thrown by `XProcRunnable.run()`, even if it is non-checked, just for documentation purposes?
